# Generated by Django 2.2.4 on 2019-10-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=50, null=True)),
                ('lasttime', models.DateTimeField()),
                ('img', models.CharField(max_length=100, null=True)),
                ('userInfo', models.TextField(null=True)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catid', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('title_font_color', models.CharField(max_length=10)),
                ('thumb', models.CharField(max_length=300)),
                ('num', models.IntegerField()),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='news_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsid', models.IntegerField()),
                ('content', models.TextField()),
                ('contentTime', models.DateTimeField()),
            ],
            options={
                'db_table': 'news_content',
            },
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='position_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionid', models.IntegerField()),
                ('newsid', models.IntegerField()),
            ],
            options={
                'db_table': 'position_content',
            },
        ),
    ]
